# You can override the name from the repository
name: Bot Skills - Bkper x API

# Set your logo url from public host. Best fit 200x200 px. Use https:// 
logo: https://w7.pngwing.com/pngs/809/699/png-transparent-chatbot-facebook-messenger-facebook-inc-internet-bot-facebook-blue-logo-online-chat.png
#Icon created by Iconchease from Non Project. Please use with right licensing.

# The Client ID from GCP project Web Application OAuth Credential
clientId: 476296195771-6uj6db05b9i2q31d4rl12jbtsjbmb46h.apps.googleusercontent.com

# The Google Apps Script ID
scriptId: 1hgGkYbb-HU9uWcvosWMNzok3qiRQt8dbDn9w5hV3ZyBhWPoZGgUQZ3wH

# The OAuth scopes used by the Google Apps Script - found at File > Project Properties > Scopes
scopes: >
    https://www.googleapis.com/auth/userinfo.email
    https://www.googleapis.com/auth/script.external_request

# The Google Apps Script trigger functions
triggers: >
    onTransactionPosted
    onTransactionDeleted
    onTransactionRestored
    onTransactionUnchecked
    TestCheck

# The version of Bkper API in which the payload will be formatted
apiVersion: v2

# The Google Apps Script API Deployment ID
deploymentId: AKfycbyolaYh96udyAGvZ6SO8xMJg5tAm8XL9jNtIYnz41Ncd1ESEGnY

# By default the App will be available to your user, or all users of your G Suite domain.
# Additionally you can yhitelist users you want this app to show up:

