# You can override the name from the repository
name: Bot Skills Bkper

# Set your logo url from public host. Best fit 200x200 px. Use https:// 
logo: https://images-platform.99static.com//8w6xifPmAUiFiQpRZO4Ki4ttBD4=/266x252:1228x1214/fit-in/500x500/99designs-contests-attachments/85/85279/attachment_85279070
#Icon created by Iconchease from Non Project. Please use with right licensing.

# The Client ID from GCP project Web Application OAuth Credential
clientId: 340850467661-52asovne28r2vvli5bviootvkig99d9h.apps.googleusercontent.com

# The Google Apps Script ID
scriptId: 1wVGGaVXGLCip3ZfOS4AG2a1gimfMKH7eA3kgZ8K64On77qIfSvrdObb9

# The OAuth scopes used by the Google Apps Script - found at File > Project Properties > Scopes
scopes: >
    https://www.googleapis.com/auth/userinfo.email
    https://www.googleapis.com/auth/script.external_request

# The Google Apps Script trigger functions
triggers: >
    onTransactionPosted
    onTransactionDeleted
    onTransactionRestored

# The version of Bkper API in which the payload will be formatted
apiVersion: v2

# The Google Apps Script API Deployment ID
deploymentId: AIzaSyAPLr3C4YnyhQiRrVpQy0lfvef_36_TI8g

# By default the App will be available to your user, or all users of your G Suite domain.
# Additionally you can yhitelist users you want this app to show up:

